services:
  - type: web
    name: codeflow-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: GITHUB_APP_ID
        sync: false
      - key: GITHUB_INSTALLATION_ID
        sync: false
      - key: GITHUB_PRIVATE_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
